---@class Options
---@field transparent boolean
---@field italics table<string, boolean>
---@field italics.comments boolean
---@field italics.keywords boolean
---@field italics.functions boolean
---@field italics.strings boolean
---@field italics.variables boolean
---@field italics.bufferline boolean
---@field overrides table<string, table<string, string>> | function(options: Options): table<string, table<string, string>>
